package br.com.ppw.dma;

import br.com.ppw.dma.evidencia.EvidenciaService;
import br.com.ppw.dma.job.ComandoSql;
import lombok.extern.slf4j.Slf4j;
import lombok.val;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.List;

@SpringBootTest
@Slf4j
class DetMakerApplicationTests {

	@Autowired
	EvidenciaService evidenciaService;

	@Test
	void testandoExtracaoBanco() {
//		val campos = List.of( "DMACCT"); //"DMACCTG",
		val campos = List.of("DMACDT1_4", "DMACDT2_4", "DMACDT3_4", "DMACSC1_4", "DMACSC2_4", "DMACSC3_4", "DMACAC1_5", "DMACAC2_5", "DMACAC3_5", "DMACRC1_5", "DMACRC2_5", "DMACRC3_5", "DMACLC1_5", "DMACLC2_5", "DMACLC3_5", "DMACDT1_5", "DMACDT2_5", "DMACDT3_5", "DMACSC1_5", "DMACSC2_5", "DMACSC3_5", "DMOFFREF", "DMPRVOFF", "DMPRVOREF", "DMEMAIL", "DMCPHONE", "DMADDR3", "DMBADDR3", "DMPEXT", "DMACODE", "DMBACODE", "DMCACODE", "DMQUE5", "DMQUE6", "DMPREVQ5", "DMPREVQ6", "DMQCHGDT5", "DMQCHGDT6", "DMAGNUMBK", "DMAGPCT", "DMAGPPSTATUS", "DMAGSTATUS", "DMAGTYPE", "DMAGAMT", "DMAGCHGDT", "DMAGINIPAYDT", "DMAGLSTPAYDT", "DMPKID", "DMPKSTATUS", "DMCPEXT", "DMADDR4", "DMSPHONE", "DMBADDRLNG", "DMBADDRLAT", "DMCLASSDT", "DMCYBSCR", "DMSCRDT", "DMADDRLNG", "DMADDRLAT", "DMACCTG", "DMACCT", "DMWKFLAG", "DMSEQNO", "DMSTATUS", "DMNXTCON", "DMQUE", "DMPRI", "DMPREVQ", "DMQCHGDT", "DMSUPV", "DMSUPCOM", "DMSCODE", "DMREVCOD", "DMREASSG", "DMPPFLAG", "DMPPMADE", "DMPPDUE", "DMPPAMT", "DMPPKEPT", "DMPPBROK", "DMPAYDT", "DMPAYAMT", "DMLTRDT", "DMLTRAMT", "DMCCSDT", "DMINACCT", "DMREACT", "DMHOSTUP", "DMLCLUPD", "DMHISTDT", "DMLAFLG", "DMAMTDLQ", "DMDLQDT", "DMCURBAL", "DMPAYOFF", "DMDAYS", "DMOPNDT", "DMPOFTIL", "DMNXTPOF", "DMOPNAMT", "DMCRLIMT", "DMPTSCOR", "DMBRANCH", "DMOFFICR", "DMPROD", "DMRELFLG", "DMADL1", "DMADL2", "DMSPDESC", "DMP1", "DMP2", "DMP3", "DMNUM30", "DMNUM60", "DMNUM90", "DMNUM120", "DMNUM150", "DMNUM180", "DMLSTCON", "DMSCHDAY", "DMPMTTOT", "DMAGENCY", "DMAGNREF", "DMAGNAMT", "DMPRVAGN", "DMPRVREF", "DMPRVAMT", "DMENTRY", "DMNUMPLC", "DMRESV1", "DMRESV2", "DMSALCD", "DMNAME", "DMNAME2", "DMADDR1", "DMADDR2", "DMCITY", "DMSTATE", "DMZIP", "DMPHONE", "DMBNAME", "DMBADDR1", "DMBADDR2", "DMBCITY", "DMBSTATE", "DMBZIP", "DMBPHONE", "DMBPEXT", "DMSSNUM", "DMPRVNAM", "DMPRVNM2", "DMPRVAD1", "DMPRVAD2", "DMPRVCTY", "DMPRVSTA", "DMPRVZIP", "DMRESV3", "DMID", "DMLASTAC", "DMLASTRC", "DMLASTLC", "DMLSTACT", "DMPRVAGN1", "DMPRVREF1", "DMPRVAMT1", "DMPRVAGN2", "DMPRVREF2", "DMPRVAMT2", "DMPRVAGN3", "DMPRVREF3", "DMPRVAMT3", "DMPRVAGN4", "DMPRVREF4", "DMPRVAMT4", "DMPRVAGN5", "DMPRVREF5", "DMPRVAMT5", "DMQUE2", "DMQUE3", "DMQUE4", "DMPREVQ2", "DMPREVQ3", "DMPREVQ4", "DMQCHGDT2", "DMQCHGDT3", "DMQCHGDT4", "DMAGNREJ", "DMSUBSET", "DMASSAGCY", "DMASSAGDT", "DMCHID", "DMSAMPLE", "DMACAC1", "DMACAC2", "DMACAC3", "DMACRC1", "DMACRC2", "DMACRC3", "DMACLC1", "DMACLC2", "DMACLC3", "DMACDT1", "DMACDT2", "DMACDT3", "DMACSC1", "DMACSC2", "DMACSC3", "DMINTDT", "DMACUMINT", "DMPRVIDT", "DMPRVAINT", "DMPRVINT", "DMCOMPANY", "DMLABEL1", "DMLABEL2", "DMLABEL3", "DMLABEL4", "DMLABEL5", "DMLABEL6", "DMACAC1_2", "DMACAC2_2", "DMACAC3_2", "DMACRC1_2", "DMACRC2_2", "DMACRC3_2", "DMACLC1_2", "DMACLC2_2", "DMACLC3_2", "DMACDT1_2", "DMACDT2_2", "DMACDT3_2", "DMACSC1_2", "DMACSC2_2", "DMACSC3_2", "DMACAC1_3", "DMACAC2_3", "DMACAC3_3", "DMACRC1_3", "DMACRC2_3", "DMACRC3_3", "DMACLC1_3", "DMACLC2_3", "DMACLC3_3", "DMACDT1_3", "DMACDT2_3", "DMACDT3_3", "DMACSC1_3", "DMACSC2_3", "DMACSC3_3", "DMACAC1_4", "DMACAC2_4", "DMACAC3_4", "DMACRC1_4", "DMACRC2_4", "DMACRC3_4", "DMACLC1_4", "DMACLC2_4", "DMACLC3_4");
		val tabela = "DELQMST";

		val comandosSql = List.of(new ComandoSql(null, tabela, null));
		evidenciaService.extractTable(comandosSql);
	}

}
